# run: conda env create --file environment.yml
name: bmex
dependencies:
- python>=3.9
- anaconda
- pip
- numpy
- tensorflow
- gunicorn
- pandas
- scikit-learn
- scipy
- pip:
  - tables
  - plotly>=5.13.0
  - dash>=1.0.0
  - colorlover>=0.2.1
  - dash-bootstrap-components==1.0.2
  - kaleido
  - dash_breakpoints
